# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

stages:
- stage: Validation
  displayName: Code validation
  jobs:
  - job: samplebranch_validation
    displayName: CIEUGWInterface Validation
  
    pool:
     vmImage: ubuntu-latest
 
    steps:

    - task: GoTool@0
      displayName: "Require Go 1.16"
      inputs:
        version: $(go_version)

